kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginxcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxcp
  template:
    metadata:
      labels:
        app: nginxcp
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
   name: nginx-svc
   labels:
      app: nginxcp
spec:
   type: NodePort
   ports:
     - nodePort: 31113
       port: 80
       targetPort: 80
   selector:
       app: nginxcp
