--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      labels:
        app: hello-whale-app
        version: blue
      name: hello-blue-whale-pod
    spec:
      containers:
        - image: 'cpbarik1/hellowhale:latest'
          name: hello-whale-container
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service 
metadata:
   name: hello-whale-svc
   labels:
      app: hello-whale-app
spec:
   type: NodePort
   ports:
     - nodePort: 31113
       port: 80
       targetPort: 80
   selector:
       app: hello-whale-app
       version: blue
